stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
      - config/paths_config.py
    outs:
      - data/ingested

  data_processing:
    cmd: python src/data_processing.py
    deps:
      - src/data_processing.py
      - config/paths_config.py
    outs:
      - data/processed/processed_data.csv

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - src/feature_engineering.py
      - config/paths_config.py
      - data/processed/processed_data.csv
    outs:
      - data/engineered_data/final_df.csv

  model_training:
    cmd: python src/model_training.py
    deps:
      - src/model_training.py
      - config/paths_config.py
      - data/engineered_data/final_df.csv
    outs:
      - data/model/trained_model.pkl